# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pigpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='pigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ration_amount', models.CharField(default=2000, max_length=4)),
                ('date', models.DateTimeField(auto_now=True)),
                ('pigpen', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pigs.Pigpen')),
            ],
        ),
        migrations.CreateModel(
            name='pigsinpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pigs', models.CharField(max_length=3)),
                ('date', models.DateTimeField(auto_now=True)),
                ('pigpen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigs.Pigpen')),
            ],
        ),
        migrations.CreateModel(
            name='Ration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ration_text', models.CharField(max_length=2)),
                ('milo', models.CharField(max_length=4)),
                ('sbm', models.CharField(max_length=4)),
                ('dynamin', models.CharField(max_length=3)),
                ('pigpak', models.CharField(max_length=3)),
                ('sixtyeighty', models.CharField(max_length=3)),
                ('control', models.CharField(max_length=3)),
                ('optimax', models.CharField(max_length=3)),
                ('molderase', models.CharField(max_length=3)),
                ('hitpork', models.CharField(max_length=3)),
                ('oats', models.CharField(max_length=3)),
                ('sowonehundred', models.CharField(max_length=3)),
                ('porkperformance', models.CharField(max_length=3)),
                ('safeguard', models.CharField(max_length=3)),
                ('spicepak', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='pigration',
            name='ration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigs.Ration'),
        ),
    ]
