# Generated by Django 2.0.1 on 2018-01-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ration',
            name='commodity',
        ),
        migrations.AddField(
            model_name='ration',
            name='milo',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='ration',
            name='sbm',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
