# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-27 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ration',
            name='60/80 w/lysine',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='Control',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='Dynamin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='H.I.T Pork Premix',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='Milo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='Mold Erase',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='Oats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='Optimax',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='Pig Pak 80 Premix',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='Pork Performance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='Sow 100 Premix',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='Soy Bean Meal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
