# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0002_auto_20170318_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ration',
            name='control',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='ration',
            name='dynamin',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='ration',
            name='hitpork',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='ration',
            name='molderase',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='ration',
            name='oats',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='ration',
            name='optimax',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='ration',
            name='pigpak',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='ration',
            name='porkperformance',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='ration',
            name='safeguard',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='ration',
            name='sixtyeighty',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='ration',
            name='sowonehundred',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='ration',
            name='spicepak',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
