# Generated by Django 2.0.1 on 2018-02-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0002_auto_20180127_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pigpen',
            options={'ordering': ['pen']},
        ),
        migrations.RenameField(
            model_name='ration',
            old_name='Sow 100 Premix',
            new_name='Pig Pak 80',
        ),
        migrations.RenameField(
            model_name='ration',
            old_name='60/80 w/lysine',
            new_name='Sow 100',
        ),
        migrations.RenameField(
            model_name='ration',
            old_name='Dynamin',
            new_name='dynamin',
        ),
        migrations.RenameField(
            model_name='ration',
            old_name='H.I.T Pork Premix',
            new_name='sbm',
        ),
        migrations.RenameField(
            model_name='ration',
            old_name='Mold Erase',
            new_name='sixtyeighty',
        ),
        migrations.RemoveField(
            model_name='pigpen',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ration',
            name='Oats',
        ),
        migrations.RemoveField(
            model_name='ration',
            name='Optimax',
        ),
        migrations.RemoveField(
            model_name='ration',
            name='Pig Pak 80 Premix',
        ),
        migrations.RemoveField(
            model_name='ration',
            name='Soy Bean Meal',
        ),
        migrations.AddField(
            model_name='ration',
            name='Hit Pork',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pigpen',
            name='pen',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
