# Generated by Django 2.0.1 on 2018-02-11 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0002_auto_20180209_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='pigletoperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('b', 'bred'), ('o', 'open'), ('f', 'farrowing'), ('w', 'wean')], default='o', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='piglets',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='sows',
            name='status',
        ),
        migrations.AddField(
            model_name='status',
            name='sow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigs.Sows'),
        ),
        migrations.AddField(
            model_name='pigletoperation',
            name='piglet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigs.piglets'),
        ),
    ]
