# Generated by Django 2.0.1 on 2018-02-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0003_auto_20180210_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='sow',
            new_name='Sow',
        ),
        migrations.AlterField(
            model_name='piglets',
            name='culled',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piglets',
            name='dead',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piglets',
            name='wean',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piglets',
            name='wean_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('bred', 'bred'), ('open', 'open'), ('farrowing', 'farrowing'), ('wean', 'wean')], default='open', max_length=50),
        ),
    ]
