# Generated by Django 2.0.1 on 2018-01-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0003_ration_dynamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ration',
            name='ration_price',
            field=models.DecimalField(decimal_places=4, editable=False, max_digits=19),
        ),
    ]
