# Generated by Django 2.0.1 on 2018-02-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0003_auto_20180202_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sows',
            fields=[
                ('sow_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('secondary_id', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='ration',
            old_name='Milo',
            new_name='milo',
        ),
    ]
