# Generated by Django 2.0.1 on 2018-01-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0004_auto_20180118_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ration',
            name='ration_price',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
