# Generated by Django 2.0.1 on 2018-02-11 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0004_auto_20180211_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='boars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boar_number', models.PositiveIntegerField()),
                ('boar_secondaryid', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='statusoptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pigletoperation',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigs.operation'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigs.statusoptions'),
        ),
        migrations.AddField(
            model_name='status',
            name='by_boar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pigs.boars'),
        ),
    ]
