# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0004_auto_20170325_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigsinpen',
            name='date',
            field=models.DateField(),
        ),
    ]
