# Generated by Django 2.0.1 on 2018-02-08 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0004_auto_20180207_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='piglets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born_date', models.DateField()),
                ('born', models.PositiveIntegerField()),
                ('alive', models.PositiveIntegerField()),
                ('dead', models.PositiveIntegerField()),
                ('culled', models.PositiveIntegerField()),
                ('wean', models.PositiveIntegerField()),
                ('operation', models.CharField(max_length=50)),
                ('wean_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='sows',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='piglets',
            name='Sow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigs.Sows'),
        ),
    ]
