# Generated by Django 2.0.1 on 2018-01-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0005_auto_20180118_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='ration',
            name='sixtyeighty',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
