# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0007_pigsinpen_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigsinpen',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
