# Generated by Django 2.0.1 on 2018-01-19 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0007_ration_hit pork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ration',
            name='Hit Pork',
        ),
        migrations.RemoveField(
            model_name='ration',
            name='dynamin',
        ),
        migrations.RemoveField(
            model_name='ration',
            name='milo',
        ),
        migrations.RemoveField(
            model_name='ration',
            name='sbm',
        ),
        migrations.RemoveField(
            model_name='ration',
            name='sixtyeighty',
        ),
        migrations.AddField(
            model_name='ration',
            name='commodity',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='pigs.Commodity', to_field='name'),
            preserve_default=False,
        ),
    ]
