# Generated by Django 2.0.1 on 2018-02-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0007_auto_20180215_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ration',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
