# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0008_auto_20170325_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigsinpen',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
