# Generated by Django 2.0.1 on 2018-03-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0008_auto_20180215_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ration',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='shipped',
            name='deadculls',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
