# Generated by Django 2.0.1 on 2018-01-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0008_auto_20180118_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ration',
            name='commodity',
        ),
        migrations.AddField(
            model_name='ration',
            name='Hit Pork',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='dynamin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='milo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='sbm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='sixtyeighty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
