# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0009_auto_20170325_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='ration',
            name='feed_per_pig',
            field=models.CharField(default=55, max_length=3),
        ),
    ]
