# Generated by Django 2.0.1 on 2018-01-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0009_auto_20180119_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ration',
            name='ration_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
    ]
