# Generated by Django 2.0.1 on 2018-03-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0009_auto_20180326_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='weanedpiglets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born_date', models.DateField()),
                ('weaned', models.PositiveIntegerField()),
                ('dead', models.PositiveIntegerField()),
                ('culled', models.PositiveIntegerField()),
                ('wean_date', models.DateField()),
                ('Sowid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigs.Sows')),
            ],
        ),
        migrations.AddField(
            model_name='ration',
            name='Selenium',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='Sow 100 W/Hit Pork',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='Spice Pak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
