# Generated by Django 2.0.3 on 2018-04-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0010_auto_20180327_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ration',
            name='60/80 w/lysine',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='Control',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='Dynamin',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='H.I.T Pork Premix',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='Milo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='Mold Erase',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='Oats',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='Optimax',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='Pig Pak 80 Premix',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='Pork Performance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='Selenium',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='Sow 100 Premix',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='Sow 100 W/Hit Pork',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='Soy Bean Meal',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='Spice Pak',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
