# Generated by Django 2.0.1 on 2018-01-20 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0010_auto_20180119_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ration',
            name='ration_price',
        ),
    ]
