# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0010_ration_feed_per_pig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigsinpen',
            name='pigs',
            field=models.IntegerField(max_length=3),
        ),
    ]
