# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0011_auto_20170527_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigration',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
