# Generated by Django 2.0.1 on 2018-01-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0011_remove_ration_ration_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ration',
            name='Control',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
