# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0012_auto_20170527_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigration',
            name='ration_amount',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='pigsinpen',
            name='pigs',
            field=models.IntegerField(),
        ),
    ]
