# Generated by Django 2.0.1 on 2018-01-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0012_ration_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='ration',
            name='Pig Pak 80',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='Pork Performance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ration',
            name='Sow 100',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
