# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0013_auto_20170529_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigration',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
