# Generated by Django 2.0.1 on 2018-01-25 03:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0013_auto_20180119_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigration',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
