# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0015_auto_20170601_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='ration',
            name='ration_price',
            field=models.IntegerField(default=55),
        ),
        migrations.AlterField(
            model_name='pigsinpen',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
