# Generated by Django 2.0.1 on 2018-01-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0016_pigration_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigration',
            name='uuid',
        ),
    ]
