# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0023_auto_20170602_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ration',
            name='ration_price',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
