# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0024_auto_20170602_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigration',
            name='pigsinpen',
            field=models.CharField(default=2, max_length=4),
        ),
    ]
