# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0026_auto_20170602_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigsinpen',
            name='pig_cost_total',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=6),
        ),
    ]
