# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0028_auto_20170608_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigration',
            name='ration_amount',
            field=models.IntegerField(),
        ),
    ]
