# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0029_auto_20170608_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigsinpen',
            name='pig_ration_cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
