# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0032_auto_20170612_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pigpen', models.PositiveIntegerField()),
                ('pigs', models.PositiveIntegerField()),
                ('pig_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ration_amount', models.PositiveIntegerField()),
                ('pig_ration_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipped_date', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
