# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0034_pigsinpen_pig_ration_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pigration',
            old_name='pigsinpen',
            new_name='pigsinapen',
        ),
        migrations.RemoveField(
            model_name='pigsinpen',
            name='pig_ration_amount',
        ),
        migrations.AddField(
            model_name='pigsinpen',
            name='totalration',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pigs.pigration'),
            preserve_default=False,
        ),
    ]
