# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0038_remove_pigration_pigs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigsinpen',
            name='pig_ration_cost',
        ),
    ]
