# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0039_remove_pigsinpen_pig_ration_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='deadculled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pigpen', models.PositiveIntegerField()),
                ('dead', models.PositiveIntegerField(blank=True, null=True)),
                ('culled', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
