# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0040_deadculled'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadculled',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
