# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0042_auto_20170617_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadculled',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shipped',
            name='ration_amount',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shipped',
            name='shipped_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
