# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-06 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0046_auto_20170705_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigration',
            name='ration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigs.Ration', to_field='ration_text'),
        ),
        migrations.AlterField(
            model_name='ration',
            name='ration_text',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
